name: Auto Update Prices

on:
  workflow_dispatch:
  schedule:
  # รันทุก 30 นาที ตั้งแต่ 13:00 - 22:00 UTC (เท่ากับ 20:00 - 05:00 น. เวลาไทย) วันจันทร์ - ศุกร์
  - cron: '*/30 13-22 * * 1-5'
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - run: python update_prices.py
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
