name: Auto Update Prices

on:
  workflow_dispatch:
  schedule:
  # รันทุก 30 นาที ตั้งแต่ 20:00 - 23:30 น. เวลาไทย (วันจันทร์ - ศุกร์)
  - cron: '*/30 20-23 * * 1-5'

  # รันอีก 1 ครั้ง ตอนปิดตลาดหุ้นสหรัฐฯ (เวลาไทย) ของวันทำการนั้นๆ
  # ปิดตี 3 (ช่วง มี.ค. - พ.ย.) -> รันเช้ามืดวันอังคาร - เสาร์
  - cron: '0 3 * * 2-6'
  # ปิดตี 4 (ช่วง พ.ย. - มี.ค.) -> รันเช้ามืดวันอังคาร - เสาร์
  - cron: '0 4 * * 2-6'

  # รันอีก 1 ครั้ง ตอนปิดตลาดหุ้นสหรัฐฯ (เวลาไทย)
  # ปิดตี 3 (ช่วงฤดูร้อน Daylight Saving: มี.ค. - พ.ย.) รันวันอังคาร - เสาร์
  - cron: '0 3 * * 2-6'
  # ปิดตี 4 (ช่วงฤดูหนาว Standard Time: พ.ย. - มี.ค.) รันวันอังคาร - เสาร์
  - cron: '0 4 * * 2-6'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - run: python update_prices.py
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
